version: '3.1'
services:
  casdoor:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: STANDARD
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "18001:8000"
    environment:
      RUNNING_IN_DOCKER: "true"
      CASDOOR_DATA_SOURCE_NAME: ${CASDOOR_DATA_SOURCE_NAME}
    volumes:
      - ./conf:/conf/

